#!/bin/sh

### BEGIN ###
# Author: idevz
# Since: 2016/04/09
# Description:       Setup Vanilla DemoApp
### END ###

VANILLA_VERSION=0.1.0.rc5
VANILLA_VERSION_DIR_STR=0_1_0_rc
VANILLA_APP_ROOT=/data/vanilla/vademo
APP_NAME=`basename $VANILLA_APP_ROOT`
VANILLA_APP_USER=idevz
VANILLA_APP_GROUP=sina
VANILLA_RUNNING_ENV='' #default '' is for production environment
TIME_MARK=`date "+%Y_%m_%d_%H_%M_%S"`


alert()
{
    MSG=$1
    echo -e "\033[31m$MSG \033[0m\n"
}

init_vanilla_app()
{
    VANILLA_APP_ROOT=$1
    echo -e "\033[40mBegin init Vanilla App: $VANILLA_APP_ROOT \033[0m\n"
    [ -n $2 ] && VANILLA_APP_USER=$2
    [ -n $3 ] && VANILLA_APP_GROUP=$3
    [ -n $5 ] && APP_NAME=$4
    [ -n $4 ] && VANILLA_RUNNING_ENV=$5

    SERVICE_SH=$VANILLA_APP_ROOT/va-$APP_NAME-service
    VANILLA_BIN=/usr/local/bin/vanilla-$VANILLA_VERSION
    [ -d $VANILLA_APP_ROOT ] && mv -f $VANILLA_APP_ROOT $VANILLA_APP_ROOT".old_"$TIME_MARK
    [ -x $VANILLA_BIN ] && $VANILLA_BIN new $VANILLA_APP_ROOT
    if [[ !$? -eq 0 ]];then
        alert $VANILLA_BIN" is not exist, You shoud install vanilla first, to see './setup-framework -h' for more info."
        exit 1
    fi
    sed "s/#user zhoujing staff/user $VANILLA_APP_USER $VANILLA_APP_GROUP/" $VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf>$VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf.tmp
    sed "s/#user zhoujing staff/user $VANILLA_APP_USER $VANILLA_APP_GROUP/" $VANILLA_APP_ROOT/nginx_conf/va-nginx.conf>$VANILLA_APP_ROOT/nginx_conf/va-nginx.conf.tmp
    mv -f $VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf.tmp $VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf
    mv -f $VANILLA_APP_ROOT/nginx_conf/va-nginx.conf.tmp $VANILLA_APP_ROOT/nginx_conf/va-nginx.conf
    chmod +x $SERVICE_SH
    sudo $SERVICE_SH initconf $VANILLA_RUNNING_ENV
    sudo $SERVICE_SH start $VANILLA_RUNNING_ENV
    sudo $SERVICE_SH restart $VANILLA_RUNNING_ENV
    echo -e "\033[40mVanilla App: $APP_NAME is running \033[0m\n"
}

show_usage()
{
    echo -e "`printf %-16s "Usage: $0"` -h   show this help info"
    echo -e "`printf %-16s ` -a   VANILLA_APP_ROOT, app absolute path(which path to init app)"
    echo -e "`printf %-16s ` -u   VANILLA_APP_USER, user to run app"
    echo -e "`printf %-16s ` -g   VANILLA_APP_GROUP, user group to run app"
    echo -e "`printf %-16s ` -e   VANILLA_RUNNING_ENV, app running environment"
}

while getopts a:u:g:e:h OPT; do
    case "$OPT" in
        a )
            VANILLA_APP_ROOT=$OPTARG
            ;;
        u )
            VANILLA_APP_USER=$OPTARG
            ;;
        g )
            VANILLA_APP_GROUP=$OPTARG
            ;;
        e )
            VANILLA_RUNNING_ENV=$OPTARG
            ;;
        h )
            show_usage && exit 0
            ;;
        -- )
            shift break
            ;;
        ? )
            alert "ERROR: unknown argument!" && show_usage && exit 1
            ;;
    esac
done

init_vanilla_app $VANILLA_APP_ROOT $VANILLA_APP_USER $VANILLA_APP_GROUP $APP_NAME $VANILLA_RUNNING_ENV

echo
echo "You are setup $APP_NAME and using:"
echo -e "`printf %-36s "\"$VANILLA_APP_ROOT\""` ---- as vanilla app root"
echo -e "`printf %-36s "\"$VANILLA_RUNNING_ENV\""` ---- as running environment"
echo -e "`printf %-36s "\"$VANILLA_APP_USER\""` ---- as vanilla app nginx user"
echo -e "`printf %-36s "\"$VANILLA_APP_GROUP\""` ---- as vanilla app nginx group"
echo

exit 0