#!/bin/sh

### BEGIN ###
# Author: idevz
# Since: 2016/04/09
# Description:       Setup Vanilla Framework and DemoApp
### END ###

VANILLA_VERSION=0.1.0.rc5
VANILLA_VERSION_DIR_STR=0_1_0_rc
VANILLA_PROJ_ROOT=/data/vanilla
VANILLA_APP_ROOT=/data/vanilla/appdemoidevz
VANILLA_APP_USER=idevz
VANILLA_APP_GROUP=sina
VANILLA_RUNNING_ENV='' #default '' is for production environment
OPENRESTY_ROOT=/usr/local/openresty
SETUP_ACTION='af'
TIME_MARK=`date "+%Y_%m_%d_%H_%M_%S"`


alert()
{
    MSG=$1
    echo -e "\033[31m$MSG \033[0m\n"
}

install_vanilla_framework()
{
    echo -e "\033[45mBegin install Vanilla Frameowrk! \033[0m\n"
    VANILLA_PROJ_ROOT=$1
    VANILLA_FRAMEWORK_ROOT=$1/framework
    VANILLA_FRAMEWORK_V=$VANILLA_FRAMEWORK_ROOT/$VANILLA_VERSION_DIR_STR
    [ -n $2 ] && OPENRESTY_ROOT=$2
    [ ! -d $OPENRESTY_ROOT ] && alert "OPENRESTY_ROOT set ERROR, OpenResty Path "$OPENRESTY_ROOT "didn't exist" && exit 1
    VANILLA_BIN=/usr/local/bin/vanilla-$VANILLA_VERSION
    VANILLA_CONSOLE_BIN=/usr/local/bin/v-console-$VANILLA_VERSION

    [ -f $VANILLA_BIN ] && mv -f $VANILLA_BIN $VANILLA_BIN".old_"$TIME_MARK
    [ -f $VANILLA_CONSOLE_BIN ] && mv -f $VANILLA_CONSOLE_BIN $VANILLA_CONSOLE_BIN".old_"$TIME_MARK
    [ -d $VANILLA_FRAMEWORK_V ] && mv -f $VANILLA_FRAMEWORK_V $VANILLA_FRAMEWORK_V".old_"$TIME_MARK

    make clean
    ./configure --prefix=$VANILLA_FRAMEWORK_ROOT --openresty-path=$OPENRESTY_ROOT
    make install

    echo -e "\033[35mVanilla Frameowrk Installed $VANILLA_FRAMEWORK_ROOT \033[0m\n"
}

init_vanilla_app()
{
    VANILLA_APP_ROOT=$1
    echo -e "\033[40mBegin init Vanilla App: $VANILLA_APP_ROOT \033[0m\n"
    [ -n $2 ] && VANILLA_APP_USER=$2
    [ -n $3 ] && VANILLA_APP_GROUP=$3
    [ -n $4 ] && VANILLA_RUNNING_ENV=$4
    APP_NAME=`basename $VANILLA_APP_ROOT`
    SERVICE_SH=$VANILLA_APP_ROOT/va-$APP_NAME-service
    VANILLA_BIN=/usr/local/bin/vanilla-$VANILLA_VERSION
    [ -d $VANILLA_APP_ROOT ] && mv -f $VANILLA_APP_ROOT $VANILLA_APP_ROOT".old_"$TIME_MARK
    [ -x $VANILLA_BIN ] && $VANILLA_BIN new $VANILLA_APP_ROOT || alert $VANILLA_BIN" is not exist, You shoud install vanilla first, to see './setup -h' for more info."
    sed "s/#user zhoujing staff/user $VANILLA_APP_USER $VANILLA_APP_GROUP/" $VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf>$VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf.tmp
    sed "s/#user zhoujing staff/user $VANILLA_APP_USER $VANILLA_APP_GROUP/" $VANILLA_APP_ROOT/nginx_conf/va-nginx.conf>$VANILLA_APP_ROOT/nginx_conf/va-nginx.conf.tmp
    mv -f $VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf.tmp $VANILLA_APP_ROOT/nginx_conf/va-nginx-development.conf
    mv -f $VANILLA_APP_ROOT/nginx_conf/va-nginx.conf.tmp $VANILLA_APP_ROOT/nginx_conf/va-nginx.conf
    chmod +x $SERVICE_SH
    sudo $SERVICE_SH initconf $VANILLA_RUNNING_ENV
    sudo $SERVICE_SH start $VANILLA_RUNNING_ENV
    sudo $SERVICE_SH restart $VANILLA_RUNNING_ENV
    echo -e "\033[40mVanilla App: $APP_NAME is running \033[0m\n"
}

show_usage()
{
    echo -e "`printf %-16s "Usage: $0"` -h   show this help info"
    echo -e "`printf %-16s ` -v   VANILLA_PROJ_ROOT, vanilla project root, will contain vanilla framework and apps"
    echo -e "`printf %-16s ` -o   OPENRESTY_ROOT, openresty install path(openresty root)"
    echo -e "`printf %-16s ` -a   VANILLA_APP_ROOT, app absolute path(which path to init app)"
    echo -e "`printf %-16s ` -u   VANILLA_APP_USER, user to run app"
    echo -e "`printf %-16s ` -g   VANILLA_APP_GROUP, user group to run app"
    echo -e "`printf %-16s ` -e   VANILLA_RUNNING_ENV, app running environment"
    echo -e "`printf %-16s ` -s   SETUP_ACTION, values 'f' for only setup framework"
    echo -e "`printf %-16s `                    values 'a' for only setup demo app default named appdemoidevz"
    echo -e "`printf %-16s `                    values 'af' for setup framework and demo app default named appdemoidevz"
}

while getopts v:o:a:u:g:eh OPT; do
    case "$OPT" in
        v )
            VANILLA_PROJ_ROOT=$OPTARG
            ;;
        o )
            OPENRESTY_ROOT=$OPTARG
            ;;
        a )
            VANILLA_APP_ROOT=$OPTARG
            ;;
        u )
            VANILLA_APP_USER=$OPTARG
            ;;
        g )
            VANILLA_APP_GROUP=$OPTARG
            ;;
        e )
            VANILLA_RUNNING_ENV=$OPTARG
            ;;
        s )
            SETUP_ACTION=$OPTARG
            ;;
        h )
            show_usage && exit 0
            ;;
        -- )
            shift break
            ;;
        ? )
            alert "ERROR: unknown argument!" && show_usage && exit 1
            ;;
    esac
done

[ -n "$VANILLA_PROJ_ROOT" ]  || $SETUP_ACTION = "f" || $SETUP_ACTION = "af" && install_vanilla_framework $VANILLA_PROJ_ROOT $OPENRESTY_ROOT

[ -n "$VANILLA_APP_ROOT" ] || $SETUP_ACTION = "a" || $SETUP_ACTION = "af" && init_vanilla_app $VANILLA_APP_ROOT $VANILLA_APP_USER $VANILLA_APP_GROUP $VANILLA_RUNNING_ENV

echo
echo "You are setup Vanilla-$VANILLA_VERSION and using:"
echo -e "`printf %-36s "\"$VANILLA_RUNNING_ENV\""` ---- as vanilla app running environment"
echo -e "`printf %-36s "\"$OPENRESTY_ROOT\""` ---- as OpenResty install path(OpenResty root)"
echo -e "`printf %-36s "\"$VANILLA_PROJ_ROOT\""` ---- as vanilla project root(will contain vanilla framework and apps)"
echo -e "`printf %-36s "\"$VANILLA_APP_USER\""` ---- as vanilla app nginx user"
echo -e "`printf %-36s "\"$VANILLA_APP_GROUP\""` ---- as vanilla app nginx group"
echo -e "`printf %-36s "\"$VANILLA_APP_ROOT\""` ---- as vanilla app root"
echo

exit 0